<?php

namespace ReclamationBundle\Repository;

/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindAll($input)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT c FROM ReclamationBundle:reclamation c WHERE c.type = '$input'   ");
        return $query->getResult();
    }
}
