<?php

namespace ReclamationBundle\Repository;

/**
 * reponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reponseRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindAll($input)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT c FROM ReclamationBundle:reponse c WHERE c.reponse = '$input'");
        return $query->getResult();
    }
}
