<?php

namespace ShopBundle\Repository;

/**
 * AddresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddresseRepository extends \Doctrine\ORM\EntityRepository
{
}
