<?php

namespace ShopBundle\Repository;

/**
 * PanierVenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierVenduRepository extends \Doctrine\ORM\EntityRepository
{
}
