materiel:
    resource: "@MaterielBundle/Resources/config/routing.yml"
    prefix:   /materielle

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

shop_admin:
    resource: "@ShopAdminBundle/Resources/config/routing.yml"
    prefix:   /shop_admin

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /shop_client

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /test

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
