shop_admin:
    resource: "@ShopAdminBundle/Resources/config/routing.yml"
    prefix:   /shop_admin

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /shop_client

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit


app:
    resource: '@AppBundle/Controller/'
    type: annotation
