shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

readProduit:
    path:     /readProduit
    defaults: { _controller: ShopBundle:Produit:read }

createPanier:
    path:     /createPanier/{id}
    defaults: { _controller: ShopBundle:Panier:create }

readPanier:
    path:     /readPanier/{id_client}
    defaults: { _controller: ShopBundle:Panier:read }

deletePanier:
    path:     /deletePanier/{id}
    defaults: { _controller: ShopBundle:Panier:delete }

updatePanier:
    path:     /updatePanier/{id}/{mod}
    defaults: { _controller: ShopBundle:Panier:update }

createCommande:
    path:     /createCommande/{idAddresse}
    defaults: { _controller: ShopBundle:Commande:create }

readCommande:
    path:     /readCommande
    defaults: { _controller: ShopBundle:Commande:read }

deleteCommande:
    path:     /deleteCommande/{id}
    defaults: { _controller: ShopBundle:Commande:delete }

createAdresse:
    path:     /createAdresse
    defaults: { _controller: ShopBundle:Commande:createAdresse }