<?php

namespace MaterielBundle\Repository;

/**
 * locationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class locationsRepository extends \Doctrine\ORM\EntityRepository
{
}
