<?php

namespace MaterielBundle\Repository;

/**
 * materielleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class materielleRepository extends \Doctrine\ORM\EntityRepository
{
}
