materiel_index:
    path:     /
    defaults: { _controller: "MaterielBundle:Materielle:index" }
    methods:  GET

materiel_show:
    path:     /{id}/show
    defaults: { _controller: "MaterielBundle:Materielle:show" }
    methods:  GET

materiel_new:
    path:     /new
    defaults: { _controller: "MaterielBundle:Materielle:new" }
    methods:  [GET, POST]

materiel_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaterielBundle:Materielle:edit" }
    methods:  [GET, POST]

materiel_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaterielBundle:Materielle:delete" }
    methods:  DELETE
ajax_search:
    path:     /search
    defaults: { _controller: "MaterielBundle:Materielle:search" }